/*****************************************************************************
* File Name: HexImage.h
**
Version: 1.0
**
Description:
* 1.) This is the header file of HexImage.c
* 2.) It provides access to the Hex file data organized as an array of constants.
* 3.) This header file is generated by the C# application "HexFile Parser" with
*     the actual hex file to be programmed as input to C# application.
**
Note:
**
Owner:
* TUSR
**
**
Related Document:
* Refer to the application note document for details on application
**
Code Tested With:
*  Microsoft Visual Studio Express 2013 for Windows Desktop (Version 12.0.21005.1 REL)
*****************************************************************************/

#ifndef __HEXIMAGE_H 
#define __HEXIMAGE_H 

/*****************************************************************************
* MACRO Definitions 
******************************************************************************/ 

#define CY8C4xx8_BL_FAMILY                    1
#define NUMBER_OF_FLASH_ROWS_HEX_FILE        1024
#define FLASH_ROW_BYTE_SIZE_HEX_FILE         256
#define FLASH_PROTECTION_BYTE_SIZE_HEX_FILE  128
#define NUMBER_OF_FLASH_ROWS_NOT_INCLUDED    307

 /*****************************************************************************
 * Global Constant Declarations 
  ****************************************************************************/
 
extern unsigned char const deviceSiliconId_HexFile[4]; 
extern unsigned char const checksumData_HexFile[2]; 
extern unsigned char const flashData_HexFile[NUMBER_OF_FLASH_ROWS_HEX_FILE - NUMBER_OF_FLASH_ROWS_NOT_INCLUDED][FLASH_ROW_BYTE_SIZE_HEX_FILE]; 
extern unsigned char const flashProtectionData_HexFile[FLASH_PROTECTION_BYTE_SIZE_HEX_FILE]; 
extern unsigned char const chipProtectionData_HexFile; 
 
extern unsigned char const flashData_HexFile_RAM[8][FLASH_ROW_BYTE_SIZE_HEX_FILE]; 
 
#endif /* __HEXIMAGE_H */ 
 
/* [] END OF FILE */ 
