/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_SWDCK_aliases.h"
#include "Pin_SWDCK.h"
#include "Pin_XRES_aliases.h"
#include "Pin_XRES.h"
#include "Pin_SWDIO_aliases.h"
#include "Pin_SWDIO.h"
#include "LCD_Char.h"
#include "Pin_Start_aliases.h"
#include "Pin_Start.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "LED_R_aliases.h"
#include "LED_R.h"
#include "LED_G_aliases.h"
#include "LED_G.h"
#include "LED_B_aliases.h"
#include "LED_B.h"
#include "PWM.h"
#include "Pin_Power_aliases.h"
#include "Pin_Power.h"
#include "Clock_1.h"
#include "Control_Reg.h"
#include "LED_R_GND_aliases.h"
#include "LED_R_GND.h"
#include "LCD_Char_LCDPort_aliases.h"
#include "LCD_Char_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

