# THIS FILE IS AUTOMATICALLY GENERATED
# Project: \\GEORGE-OFFICE2\Users\George\Box Sync\Backbone\Design\Testing\TestStation\Software\HSSP\AN84858\C_Hssp_TimeoutCalc.cydsn\C_Hssp_TimeoutCalc.cyprj
# Date: Tue, 29 Nov 2016 02:24:24 GMT
#set_units -time ns
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 15.873015873015874 -waveform {0 7.93650793650794} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 15.873015873015874 -waveform {0 7.93650793650794} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]


# Component constraints for \\GEORGE-OFFICE2\Users\George\Box Sync\Backbone\Design\Testing\TestStation\Software\HSSP\AN84858\C_Hssp_TimeoutCalc.cydsn\TopDesign\TopDesign.cysch
# Project: \\GEORGE-OFFICE2\Users\George\Box Sync\Backbone\Design\Testing\TestStation\Software\HSSP\AN84858\C_Hssp_TimeoutCalc.cydsn\C_Hssp_TimeoutCalc.cyprj
# Date: Tue, 29 Nov 2016 02:24:17 GMT
